extensions:
    ktpl-akeneo_trash-menu-trash:
        module: pim/menu/tab
        parent: pim-menu
        position: 70
        targetZone: mainMenu
        aclResourceId: ktpl_akeneo_trash_index
        config:
            title: ktpl.akeneo_trash.menu.tab.trash
            iconModifier: iconAkeneoTrash

    ktpl-akeneo_trash-menu-trash-column:
        module: pim/menu/column
        parent: pim-menu
        position: 500
        targetZone: column
        config:
            tab: ktpl-akeneo_trash-menu-trash
            navigationTitle: ktpl.akeneo_trash.navigation.trash

    ktpl-akeneo_trash-menu-trash-navigation-block:
        module: pim/menu/navigation-block
        parent: ktpl-akeneo_trash-menu-trash-column
        targetZone: navigation
        config:
            title: ktpl.akeneo_trash.navigation.trash

    ktpl-akeneo_trash-menu-trash-product:
        module: pim/menu/item
        parent: ktpl-akeneo_trash-menu-trash-navigation-block
        aclResourceId: ktpl_akeneo_trash_product_index
        position: 0
        config:
            title: pim_enrich.entity.product.plural_label
            to: ktpl_akeneo_trash_product_index