services:
    pim_datagrid.extension.mass_action.dispatcher:
        class: '%pim_datagrid.extension.mass_action.dispatcher.class%'
        arguments:
            - '@pim_datagrid.extension.mass_action.handler.registry'
            - '@oro_datagrid.datagrid.manager'
            - '@oro_datagrid.datagrid.request_params'
            - '@oro_datagrid.mass_action.parameters_parser'
            - ['product-grid', 'proposal-grid', 'published-product-grid', 'ktpl_akeneo_product_trash-grid']]

    pim_datagrid.extension.mass_action.type.product_akeneo_trash_mass_delete:
        public: true
        class: '%pim_datagrid.extension.mass_action.type.delete.class%'
        shared: false
        tags:
            - { name: oro_datagrid.extension.mass_action.type, type: akeneo_trash_mass_delete }
            
    pim_datagrid.extension.mass_action.type.product_akeneo_trash_mass_restore:
        public: true
        class: 'KTPL\AkeneoTrashBundle\MassAction\Actions\Ajax\RestoreMassAction'
        shared: false
        tags:
            - { name: oro_datagrid.extension.mass_action.type, type: akeneo_trash_mass_restore }