ktpl_akeneo_trash_product_index:
    path: '/ktpl/akeneo-trash/product/'

ktpl_akeneo_trash_product_rest_remove:
    path: /ktpl/akeneo-trash/product/rest/{id}
    defaults: { _controller: ktpl.akeneo_trash.controller.akeneo_trash:removeProductAction, _format: json }
    requirements:
        id: '[0-9a-f]+'
    methods: [DELETE]

ktpl_akeneo_trash_product_model_rest_remove:
    path: /ktpl/akeneo-trash/product-model/rest/{id}
    defaults: { _controller: ktpl.akeneo_trash.controller.akeneo_trash:removeProductModelAction, _format: json }
    requirements:
        id: '[0-9a-f]+'
    methods: [DELETE]

ktpl_akeneo_trash_rest_restore:
    path: /ktpl/akeneo-trash/restore/{resource}/{id}
    defaults: { _controller: ktpl.akeneo_trash.controller.akeneo_trash:restoreTrashAction, _format: json, resource: product}
    requirements:
        resource: '[a-zA-Z0-9_]+'
        id: '[0-9a-f]+'
    methods: [DELETE]

ktpl_akeneo_trash_rest_get_filter:
    path: 'ktpl/akeneo-trash/get-filter'
    defaults: { _controller: ktpl.akeneo_trash.controller.rest.mass_edit:getFilterAction }
    methods: [POST]
