parameters:
    ktpl.akeneo_trash.delete_products_and_product_models.tasklet_name: 'delete_products_product_models_from_trash'
    ktpl.akeneo_trash.restore_products_and_product_models.tasklet_name: 'restore_products_product_models_from_trash'
services:
    ktpl.akeneo_trash.step.delete_products_and_product_models.mass_edit:
        class: '%pim_connector.step.tasklet.class%'
        arguments:
            - '%ktpl.akeneo_trash.delete_products_and_product_models.tasklet_name%'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@ktpl.akeneo_trash.tasklet.delete_products_and_product_models'

    ktpl.akeneo_trash.tasklet.delete_products_and_product_models:
        class: 'Akeneo\Pim\Enrichment\Component\Product\Job\DeleteProductsAndProductModelsTasklet'
        arguments:
            - '@pim_catalog.query.product_and_product_model_query_builder_factory'
            - '@ktpl.akeneo_trash.remover.product'
            - '@ktpl.akeneo_trash.remover.product_model'
            - '@pim_connector.doctrine.cache_clearer'
            - '@pim_catalog.filter.chained'
            - 100
            - '@akeneo.pim.enrichment.product_model.query.count_product_models_and_children_product_models'
            - '@akeneo.pim.enrichment.product_model.query.count_variant_products'

    ktpl.akeneo_trash.step.restore_products_and_product_models.mass_edit:
        class: '%pim_connector.step.tasklet.class%'
        arguments:
            - '%ktpl.akeneo_trash.restore_products_and_product_models.tasklet_name%'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@ktpl.akeneo_trash.tasklet.restore_products_and_product_models'

    ktpl.akeneo_trash.tasklet.restore_products_and_product_models:
        class: 'KTPL\AkeneoTrashBundle\Job\RestoreProductsAndProductModelsTasklet'
        arguments:
            - '@pim_catalog.query.product_and_product_model_query_builder_factory'
            - '@ktpl.akeneo_trash.manager.akeneo_trash'
            - '@pim_connector.doctrine.cache_clearer'
            - '@pim_catalog.filter.chained'
            - 100
            - '@akeneo.pim.enrichment.product_model.query.count_product_models_and_children_product_models'
            - '@akeneo.pim.enrichment.product_model.query.count_variant_products'
            - '@akeneo_batch.job_repository'